适配paddle的compare的tensor比对
PaddlePaddle/PaddleAPEX pull request #3
Opened 2024-05-24 07:54 UTC by jianzhang96

添加了整个compare文件夹。适配了paddle.tensor的比对逻辑。

2024-05-24 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleAPEX?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleAPEX?pullRequest=3) before we can accept your contribution.<br/><hr/>**zhangjian** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleAPEX?pullRequest=3) it.</sub>

2024-05-24 09:16 UTC, SylarTiaNII requested changes
Some comments

2024-05-24 09:16 UTC, SylarTiaNII commented on Acc/compare/config.yaml
> +dump_path: './'
这个文件的作用是什么？

2024-05-24 09:16 UTC, SylarTiaNII commented on Acc/compare/api_precision_compare.py
> +def _api_precision_compare(parser=None):
主要函数入口建议不要使用_前缀

2024-05-24 09:32 UTC, jianzhang96 commented on Acc/compare/config.yaml
> +dump_path: './'
config.yaml是对脚本运行进行一些参数配置，其中
`dump_path`数据dump的路径
`real_data:`是否真实数据模式
`enable_dataloader:`训练脚本是否使用DataLoader加载数据（之前用于torch）
`white_list:`api白名单
`error_data_path`错误数据存储路径
`precision`精度设置

2024-05-24 09:35 UTC, jianzhang96 commented on Acc/compare/api_precision_compare.py
> +def _api_precision_compare(parser=None):
您好，主要函数入口没有使用_前缀，例如print_pretest_result, compare_output,record_results，用了_前缀的都是类内部使用的，服务于compare_output

2024-05-31 01:04 UTC, SylarTiaNII approved these changes
LGTM

2024-05-31 01:04 UTC, merged