数据生成，结果为exec_api的输入
PaddlePaddle/PaddleAPEX pull request #4
Opened 2024-05-24 08:14 UTC by 007-LWYing

读入dump.json，根据统计量生成cpu数据和device数据。结果是exec_api的输入。

2024-05-24 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleAPEX?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleAPEX?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleAPEX?pullRequest=4) it.</sub>

2024-05-24 09:09 UTC, SylarTiaNII requested changes
some comments

2024-05-24 09:09 UTC, SylarTiaNII commented on Acc/run_ut/run_ut.py
> +    bench_grad_out, device_grad_out = None, None
这个地方需要调用exec_api

2024-05-24 09:09 UTC, SylarTiaNII commented on Acc/run_ut/run_ut.py
> +    cpu_args, cpu_kwargs = generate_cpu_params(args, kwargs, need_backward, api_name)
我们这个地方不光期望使用cpu和npu对比，还期望使用npu和gpu的结果直接对比。需要给出上层调用的方法。

2024-05-24 09:09 UTC, SylarTiaNII commented on Acc/run_ut/run_ut_utils.py
> +hf_32_standard_api = ["conv1d", "conv2d"]
请教一下这里两个API为什么要单独拿出来？

2024-05-24 09:24 UTC, 007-LWYing commented on Acc/run_ut/run_ut.py
> +    cpu_args, cpu_kwargs = generate_cpu_params(args, kwargs, need_backward, api_name)
gpu的数据生成办法与npu一致，调用get_device_params()，把current_device改成gpu即可。只比npu和gpu，generate_cpu_params可以不用

2024-05-24 09:26 UTC, 007-LWYing commented on Acc/run_ut/run_ut_utils.py
> +hf_32_standard_api = ["conv1d", "conv2d"]
跑的是hf32，需要将fp32的数据转成hf32

2024-05-24 09:30 UTC, 007-LWYing commented on Acc/run_ut/run_ut.py
> +    bench_grad_out, device_grad_out = None, None
out = exec_api(api_type, api_name, cpu_args, cpu_kwargs)
device_out = exec_api(api_type, api_name, device_args, device_kwargs)

2024-05-25 01:27 UTC, Walker-yuan commented on Acc/run_ut/data_generate.py
> +    # 将输入的float32 tensor转为hf32 tensor，再转为float32 tensor
格式跟其他函数保持一致；
Function Description:
**
Parameter:
**

2024-05-31 01:05 UTC, SylarTiaNII approved these changes
LGTM

2024-05-31 01:05 UTC, merged